name: Executar fetch_all_sales.js

on:
  schedule:
    - cron: '0 * * * *' # Executa a cada hora (ajuste conforme necessário)
  workflow_dispatch: # Permite execução manual

jobs:
  execute-sales-fetch:
    runs-on: ubuntu-latest

    steps:
    # 1. Fazer checkout do repositório
    - name: Checkout do repositório
      uses: actions/checkout@v3

    # 2. Configurar Node.js
    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # 3. Instalar dependências
    - name: Instalar dependências
      run: npm install

    # 4. Executar o script fetch_all_sales.js
    - name: Executar o script
      run: node fetch_all_sales.js
