name: Atualizar Vendas e Google Sheets

on:
  schedule:
    - cron: '*/5 * * * *' # Executa a cada 5 minutos (ajuste conforme necessário)
  workflow_dispatch: # Permite execução manual

jobs:
  update-sales:
    runs-on: ubuntu-latest

    steps:
    # 1. Fazer checkout do repositório
    - name: Checkout do repositório
      uses: actions/checkout@v3

    # 2. Configurar Node.js
    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # 3. Instalar dependências
    - name: Instalar dependências
      run: npm install

    # 4. Executar fetch_all_sales.js
    - name: Executar fetch_all_sales.js
      run: node fetch_all_sales.js

    # 5. Enviar dados para o Google Sheets
    - name: Enviar dados para o Google Sheets
      run: |
        curl -X POST \
        -H "Content-Type: application/json" \
        -d @all_sales.json \
        "https://script.google.com/macros/s/AKfycbxq-nGLHJOsoHYcAQKTXw5u1qXXHz00p_Cq7c6JJhdtBge8la4zb2ThiUSUabwc6Lc-/exec"
